### ISSUE TITLE
Dont download the image if it already exists

### ISSUE THREAD

**Issue by isi-lincoln** [rcgoodfellow/raven-images#3]
If the image already exists in base/ the make file should not re-download the image.  Wget will append the number to the file for the new download, and all the other scripts will only look for the name of the file rather than the most current version.

Also, if the most current version differs, the sha would differ.  So there is no point to downloading the image if it already exists in base.  I believe this can be accomplished in the Makefile using:

```
base/$(UBUNTU_1604): base
ifneq (,$(wildcard $(UBUNTU_1604)))
       wget --directory-prefix base ${UBUNTU_URL}
endif
```

Example behavior after calling `make` multiple times:
```
lthurlow@ubuntu:~/raven-images$ ls base/
ubuntu-16.04-server-cloudimg-amd64-disk1.img  ubuntu-16.04-server-cloudimg-amd64-disk1.img.1
```

**Comment by rcgoodfellow** [comment]
Fixed in 78c83d20e57bf7026684885b483b0db8d0e45930 by using [order-only-dependences](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types)
